name: flutter_shell_orchestrator
description: "Shell Orquestador de MFE en WebView con Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # NavegaciÃ³n
  go_router: ^13.0.0

  # WebView
  flutter_inappwebview: ^6.0.0

  # Red (para futuras implementaciones)
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
